
name: Rust

on:
  push:
    paths:
      - 'firmware/**'
      - '.github/workflows/rust.yml'
  pull_request:
    paths:
      - 'firmware/**'

defaults:
  run:
    working-directory: firmware/src

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      RUSTDOCFLAGS: -Dwarnings
    strategy:
      matrix:
        rust:
          - stable
    steps:
    - uses: actions/checkout@v4

    - name: Install ARM toolchain
      run: rustup target add thumbv6m-none-eabi

    - name: Build
      run: cargo check --release --verbose

    - name: Run tests
      run: cargo test --lib --target=x86_64-unknown-linux-gnu --verbose

    - name: Check Fmt
      run: cargo fmt --all -- --check

    - name: Clippy
      continue-on-error: true
      run: cargo clippy --all-targets -- -D warnings -A clippy::new_ret_no_self
